sources:
  - name: source
    database: dbt_tutorial  # Our catalog name in databricks is "dbt_tutorial"
    schema: source  # Our schema name in databricks is "source"
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer
